name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy site to GCS
    runs-on: ubuntu-latest
    environment: gcs-site-deploy
    steps:
      - uses: actions/checkout@v2

      - name: Sync
        uses: patrickwyler/gcs-bucket-sync-action@1.3
        with:
          secrets: ${{ secrets.google_service_account_credentials }}
          bucket: 'makeagrocerylist.com'
          exclude: '.*\.md$|\.gitignore$|\.git/.*$|\.github/.*$|.*\.py$|Dockerfile|.*\.txt$'
